name: Run Tests on Merge

on: workflow_dispatch

jobs:
  unit-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Set environment variables
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          NEXT_PUBLIC_TEST_USER: ${{ secrets.NEXT_PUBLIC_TEST_USER }}
          NEXT_PUBLIC_TEST_PASSWORD: ${{ secrets.NEXT_PUBLIC_TEST_PASSWORD }}
          NEXT_PUBLIC_TEST_USER_ID: ${{ secrets.NEXT_PUBLIC_TEST_USER_ID }}
          NEXT_PUBLIC_TEST_ARTICLE_ID: ${{ secrets.NEXT_PUBLIC_TEST_ARTICLE_ID }}
          NEXT_PUBLIC_REDIRECT_URL: ${{ secrets.NEXT_PUBLIC_REDIRECT_URL }}
          NEXT_PUBLIC_QIITA_API_TOKEN: ${{ secrets.NEXT_PUBLIC_QIITA_API_TOKEN }}
          NEXT_PUBLIC_FORM_URL: ${{ secrets.NEXT_PUBLIC_FORM_URL }}
        run: echo "Environment variables are set"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build the project
        run: pnpm build

      - name: Run Unit tests
        run: pnpm test

      - name: Start application
        run: pnpm start &

      - name: Wait for application
        run: npx wait-on http://localhost:3000

      - name: Run E2E tests
        run: pnpm e2e
